import NavBar from '@/components/NavBar';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Festive Calendar',
  description: 'Generated by Codepub',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={``}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
